name: 'Write Version To File'
description: 'Writes version information to a structured JSON file and commits the file'
inputs:
  version:
    description: The version number to use
    required: true
  path:
    description: The path to the version file to output
    required: true
  user-email:
    description: The email of the user that commits the version file
    required: false
    default: 41898282+github-actions[bot]@users.noreply.github.com
  user-name:
    description: The name of the user that commits the version file
    required: false
    default: github-actions[bot]
  author-email:
    description: The email of the commit author. Defaults to whoever triggered this workflow run.
    required: false
    default: ${{ github.actor }}@users.noreply.github.com
  author-name:
    description: The user-name of the commit author. Defaults to whoever triggered this workflow run.
    required: false
    default: ${{ github.actor }}
  merge-strategy:
      description: How to reconcile divergent branches. Can be either 'merge'(default), 'rebase' or 'fast-forward'
      required: false
      default: 'merge'

runs:
  using: 'node16'
  main: 'release/index.js'
